---
format:
  html: 
    output-file: "infrastructure"
    output-ext:  "html"
    code-line-numbers: true
editor: source
engine: knitr
filters:
  - webr-teachr
  - quiz-teachr
webr:
  packages: ["reticulate"]
  autoload-packages: false
---

```{r setup, include=FALSE}
library(reticulate)
use_python("/usr/bin/python3")
```

# Infrastructure Exercises

This set of exercises is meant to test your knowledge of the concepts covered in block 3 of the course. All questions are Multiple Choice.

## GitHub Continuous Integration 

Look at the following `.yaml` file. This is a configuration for a Continuous Integrations Process (Github Actions in this case) for a minimal example.

::: {.callout-caution}
## Your turn!
Try to interpret what each of the lines means.
:::

```yaml
name: Basic Continuous Integration

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          packages: |
            rmarkdown
            kofdata
```


### Exercise 1

What do you think line 3 accomplishes?

:::{.quiz-multichoice}
- [ ] [When this file is run it executes `git push` ]{hint="x"}
- [X] [It runs the workflow when someone executes `git push`]{hint="o"}
- [ ] [It continuously executes `git push` until the action is successful]{hint="x"}
- [ ] [It's just here for our understanding]{hint="x"}
:::

### Exercise 2
<!-- TODO: get line numbering in yml -->
What do you think lines 11-15 do?

:::{.quiz-multichoice}
- [X] [Installs R dependencies incl. packages]{hint="o"}
- [ ] [Installs R dependencies incl. packages and then removes them]{hint="x"}
- [ ] [Links the `.yml` file to an external API that installs R packages remotely]{hint="x"}
- [ ] [Sets up a new Git repository and initializes the dependencies]{hint="x"}
:::

### Exercise 3

Which of the below is true?

:::{.quiz-multichoice}
- [ ] [The configuration file will only work for macOS systems]{hint="x"}
- [X] [It uses marketplace actions from third parties (other than GitHub) which is not transparent and may not work in the future]{hint="o"}
- [X] [marketplace actions are convenient and can do standard things effortlessly, it's a tradeoff: robustness and transparency vs. development speed and convenience]
- [ ] [It assumes the actions from lines 10 and 11 are pre-installed which may cause errors]{hint="x"}
- [ ] [The document is too short to be useful]{hint="x"}
:::

::: {.callout-tip}
## Your Turn!
If you would like to replicate the Github Actions example from above, you can find a `gha_repo.rmd` file under [https://github.com/h4sci/h4sci-tasks](https://github.com/h4sci/h4sci-tasks)
:::

## Dynamic vs. Static Tools

### Exercise 4 
<!-- wording vague... -->
Which of the following frameworks can be used to build dynamic websites?

:::{.quiz-multichoice}
- [ ] [Hugo]{hint="x"}
- [X] [Django]{hint="o"}
- [X] [Wordpress]{hint="o"}
- [ ] [Jekyll]{hint="x"}
- [X] [R/Python Shiny]{hint="o"}
:::

### Exercise 5 

Which of the following platforms is a reasonable choice to host a static website?

:::{.quiz-multichoice}
- [ ] [Wordpress.com]{hint="o"}
- [X] [Github Pages]{hint="o"}
- [X] [Netlify]{hint="o"}
:::


### Exercise 6

Which of the following are true?

:::{.quiz-multichoice}
- [X] [Dynamic websites can provide differing content for different users]{hint="x"} 
- [X] [Static websites do not need server side scripting languages or databases]{hint="x"}
- [ ] [Dynamic websites are inherently more secure because they use server-side processing]{hint="o"}
- [ ] [Dynamic hosting is always cheaper than static hosting because of server availability]{hint="o"}
:::